apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../base]
images:
  - name: ghcr.io/cap-alfamike/fraudguard
    newTag: "1.1.0"  # em CI: substituir por digest (sha256) para imutabilidade
patches:
  - target: { kind: HorizontalPodAutoscaler, name: fraudguard }
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 6
